/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emploidutemps;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author V110
 */
public class AjouterSeance extends javax.swing.JFrame {

     Connection con = null;
    /*Recherche des element dans base de donner*/
    PreparedStatement pst = null ;
    /*utilisé pour stocker les données renvoyées*/
    ResultSet rs =null;
    /*utilisé pour selection */
    Statement st = null;
    
    public AjouterSeance() {
        initComponents();
        selectionSeance();
    }
  public void selectionSeance(){
      
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/mytab","root","Yann2003");
            st = con.createStatement();
            rs = st.executeQuery("SELECT *FROM seance");
            /*Pour rensiegner les differents champ remplie dans note tableau*/
            TabAjoutSeance.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NomEnsei = new javax.swing.JLabel();
        NomMat = new javax.swing.JLabel();
        DateSean = new javax.swing.JLabel();
        HeurDeb = new javax.swing.JLabel();
        HeurFin = new javax.swing.JLabel();
        StatutSean = new javax.swing.JLabel();
        nomEnseignant = new javax.swing.JTextField();
        nomMatiere = new javax.swing.JTextField();
        dateSeance = new javax.swing.JTextField();
        heurDebut = new javax.swing.JTextField();
        heurFin = new javax.swing.JTextField();
        ajouter = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        retour = new javax.swing.JButton();
        idSeance = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        supprimer = new javax.swing.JButton();
        statutSeance = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabAjoutSeance = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ajouter Seance");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(160, 219, 242));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ajouter Seance");

        NomEnsei.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NomEnsei.setForeground(new java.awt.Color(255, 255, 255));
        NomEnsei.setText("Nom Enseignant :");

        NomMat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NomMat.setForeground(new java.awt.Color(255, 255, 255));
        NomMat.setText("Nom Matiere :");

        DateSean.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DateSean.setForeground(new java.awt.Color(255, 255, 255));
        DateSean.setText("Date Seance :");

        HeurDeb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HeurDeb.setForeground(new java.awt.Color(255, 255, 255));
        HeurDeb.setText("Heure Debut Seance :");

        HeurFin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HeurFin.setForeground(new java.awt.Color(255, 255, 255));
        HeurFin.setText("Heure Fin Seance :");

        StatutSean.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        StatutSean.setForeground(new java.awt.Color(255, 255, 255));
        StatutSean.setText("Statut Seance :");

        nomEnseignant.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nomEnseignant.setName("nomEnseignant"); // NOI18N

        nomMatiere.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nomMatiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomMatiereActionPerformed(evt);
            }
        });

        dateSeance.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        dateSeance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateSeanceActionPerformed(evt);
            }
        });

        heurDebut.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        heurFin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        ajouter.setBackground(new java.awt.Color(21, 143, 191));
        ajouter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ajouter.setForeground(new java.awt.Color(255, 255, 255));
        ajouter.setText("AJOUTER");
        ajouter.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 143, 191), 1, true));
        ajouter.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        modifier.setBackground(new java.awt.Color(21, 143, 191));
        modifier.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        modifier.setForeground(new java.awt.Color(255, 255, 255));
        modifier.setText("MODIFIER");
        modifier.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 143, 191), 1, true));
        modifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifierMouseClicked(evt);
            }
        });
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        retour.setBackground(new java.awt.Color(21, 143, 191));
        retour.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        retour.setForeground(new java.awt.Color(255, 255, 255));
        retour.setText("Retour");
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourActionPerformed(evt);
            }
        });

        idSeance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        idSeance.setForeground(new java.awt.Color(255, 255, 255));
        idSeance.setText("ID Seance");

        id.setName("id"); // NOI18N

        supprimer.setBackground(new java.awt.Color(21, 143, 191));
        supprimer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        supprimer.setForeground(new java.awt.Color(255, 255, 255));
        supprimer.setText("SUPPRIMER");
        supprimer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 143, 191), 1, true));
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        statutSeance.setText("NON EFFECTUER");
        statutSeance.setName("statut"); // NOI18N
        statutSeance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statutSeanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(retour, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(79, 79, 79))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HeurFin)
                                    .addComponent(DateSean, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StatutSean)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(idSeance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(NomMat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(NomEnsei, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(HeurDeb)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nomMatiere)
                            .addComponent(dateSeance)
                            .addComponent(nomEnseignant)
                            .addComponent(heurDebut)
                            .addComponent(heurFin)
                            .addComponent(id)
                            .addComponent(statutSeance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idSeance, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(NomEnsei, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(NomMat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DateSean, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(HeurDeb, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(HeurFin)
                        .addGap(30, 30, 30)
                        .addComponent(StatutSean, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nomEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nomMatiere, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dateSeance, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(heurDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(heurFin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(statutSeance, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ajouter)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(supprimer)
                        .addComponent(modifier)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(retour)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 600));

        TabAjoutSeance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TabAjoutSeance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID SEANCE", "NOM ENSEIGN", "NOM MATIERE", "DATE SEANCE", "HEURE DEB SEANCE", "HEURE FIN SEANCE", "STATUT SEANCE"
            }
        ));
        TabAjoutSeance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabAjoutSeanceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabAjoutSeance);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 840, 550));

        jLabel1.setBackground(new java.awt.Color(172, 240, 240));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1070, 600));

        setSize(new java.awt.Dimension(1275, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomMatiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomMatiereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomMatiereActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed

        try{
            String url = "jdbc:mysql://localhost:3306/mytab";
            con = DriverManager.getConnection(url, "root", "Yann2003");
            pst=con.prepareStatement("insert into seance values(?,?,?,?,?,?,?)");
            pst.setInt(1, Integer.parseInt((id.getText())));
            pst.setString(2,nomEnseignant.getText());
            pst.setString(3,nomMatiere.getText());
            pst.setString(4,dateSeance.getText());
            pst.setString(5,heurDebut.getText());
            pst.setString(6,heurFin.getText());
            pst.setString(7, (String) statutSeance.getText());
           
            int Row = pst.executeUpdate();
          JOptionPane.showMessageDialog(null,"Ajout effectuer");
           selectionSeance();
            
        }catch(Exception e){
          
            System.out.println(e);
        }
        
    }//GEN-LAST:event_ajouterActionPerformed

    private void retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourActionPerformed
        Accueil g = new Accueil();
        this.hide();
        g.setVisible(true);
    }//GEN-LAST:event_retourActionPerformed

    private void dateSeanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateSeanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateSeanceActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
  try{
            String url = "jdbc:mysql://localhost:3306/mytab";
            con = DriverManager.getConnection(url, "root", "Yann2003");
            pst = con.prepareStatement("UPDATE seance SET id=?, NomEnsei=?, NomSean=?, DateSean=?, HeurDeb=?, HeurFin=?, StatuSean=?  WHERE id =?");
            pst.setInt(1, Integer.parseInt((id.getText())));
            pst.setString(2,nomEnseignant.getText());
            pst.setString(3,nomMatiere.getText());
            pst.setString(4,dateSeance.getText());
            pst.setString(5,heurDebut.getText());
            pst.setString(6,heurFin.getText());
            pst.setString(7, (String) statutSeance.getText());
            pst.setInt(8, Integer.parseInt((id.getText())));
            int row = pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "seance modifier avec succes");
           selectionSeance();
            
        }catch(Exception e){
         
            System.out.println(e);}
      
    }//GEN-LAST:event_modifierActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
 if(id.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Choisissez l'utilisateur a supprimer");
        }else{
           try{
              String url = "jdbc:mysql://localhost:3306/mytab";
              con = DriverManager.getConnection(url, "root", "Yann2003");
              st = con.createStatement();
              st.executeUpdate("DELETE FROM seance WHERE id = "+id.getText());
              JOptionPane.showMessageDialog(this, "Utilisateur supprimer avec succes");
               selectionSeance();
        }catch(Exception e){
            e.printStackTrace();
        }}   
    }//GEN-LAST:event_supprimerActionPerformed

    private void TabAjoutSeanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabAjoutSeanceMouseClicked
         DefaultTableModel model = (DefaultTableModel)TabAjoutSeance.getModel();
        int myIndex = TabAjoutSeance.getSelectedRow();
         id.setText(model.getValueAt(myIndex,0).toString());
         nomEnseignant.setText(model.getValueAt(myIndex,1).toString());
         nomMatiere.setText(model.getValueAt(myIndex,2).toString());
         dateSeance.setText(model.getValueAt(myIndex,3).toString());
         heurDebut.setText(model.getValueAt(myIndex,4).toString());
        heurFin.setText(model.getValueAt(myIndex,5).toString());
         statutSeance.setText(model.getValueAt(myIndex,6).toString());
    }//GEN-LAST:event_TabAjoutSeanceMouseClicked

    private void statutSeanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statutSeanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statutSeanceActionPerformed

    private void modifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifierMouseClicked
     
    }//GEN-LAST:event_modifierMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterSeance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterSeance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterSeance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterSeance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterSeance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateSean;
    private javax.swing.JLabel HeurDeb;
    private javax.swing.JLabel HeurFin;
    private javax.swing.JLabel NomEnsei;
    private javax.swing.JLabel NomMat;
    private javax.swing.JLabel StatutSean;
    private javax.swing.JTable TabAjoutSeance;
    private javax.swing.JButton ajouter;
    private javax.swing.JTextField dateSeance;
    private javax.swing.JTextField heurDebut;
    private javax.swing.JTextField heurFin;
    private javax.swing.JTextField id;
    private javax.swing.JLabel idSeance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifier;
    private javax.swing.JTextField nomEnseignant;
    private javax.swing.JTextField nomMatiere;
    private javax.swing.JButton retour;
    private javax.swing.JTextField statutSeance;
    private javax.swing.JButton supprimer;
    // End of variables declaration//GEN-END:variables
}
